//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyberia.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyberia.Translation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carré.
        /// </summary>
        public static string CardCombination_FourOfAKind {
            get {
                return ResourceManager.GetString("CardCombination.FourOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        public static string CardCombination_None {
            get {
                return ResourceManager.GetString("CardCombination.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une paire.
        /// </summary>
        public static string CardCombination_Pair {
            get {
                return ResourceManager.GetString("CardCombination.Pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brelan.
        /// </summary>
        public static string CardCombination_ThreeOfAKind {
            get {
                return ResourceManager.GetString("CardCombination.ThreeOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double paire.
        /// </summary>
        public static string CardCombination_TwoPair {
            get {
                return ResourceManager.GetString("CardCombination.TwoPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obèse.
        /// </summary>
        public static string Corpulence_Obese {
            get {
                return ResourceManager.GetString("Corpulence.Obese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rassasié.
        /// </summary>
        public static string Corpulence_Satisfied {
            get {
                return ResourceManager.GetString("Corpulence.Satisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maigrichon.
        /// </summary>
        public static string Corpulence_Skinny {
            get {
                return ResourceManager.GetString("Corpulence.Skinny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA ≠ #1.
        /// </summary>
        public static string Criterion_ActionPoint_Different {
            get {
                return ResourceManager.GetString("Criterion.ActionPoint.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA = #1.
        /// </summary>
        public static string Criterion_ActionPoint_Equal {
            get {
                return ResourceManager.GetString("Criterion.ActionPoint.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA &lt; #1.
        /// </summary>
        public static string Criterion_ActionPoint_Inferior {
            get {
                return ResourceManager.GetString("Criterion.ActionPoint.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA &gt; #1.
        /// </summary>
        public static string Criterion_ActionPoint_Superior {
            get {
                return ResourceManager.GetString("Criterion.ActionPoint.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité ≠ #1.
        /// </summary>
        public static string Criterion_Agility_Different {
            get {
                return ResourceManager.GetString("Criterion.Agility.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité = #1.
        /// </summary>
        public static string Criterion_Agility_Equal {
            get {
                return ResourceManager.GetString("Criterion.Agility.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité &lt; #1.
        /// </summary>
        public static string Criterion_Agility_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Agility.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité &gt; #1.
        /// </summary>
        public static string Criterion_Agility_Superior {
            get {
                return ResourceManager.GetString("Criterion.Agility.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignement ≠ #1.
        /// </summary>
        public static string Criterion_Alignment_Different {
            get {
                return ResourceManager.GetString("Criterion.Alignment.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignement = #1.
        /// </summary>
        public static string Criterion_Alignment_Equal {
            get {
                return ResourceManager.GetString("Criterion.Alignment.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don ≠ #1.
        /// </summary>
        public static string Criterion_AlignmentFeat_Different {
            get {
                return ResourceManager.GetString("Criterion.AlignmentFeat.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don #1 ≠ #2.
        /// </summary>
        public static string Criterion_AlignmentFeat_Different_Level {
            get {
                return ResourceManager.GetString("Criterion.AlignmentFeat.Different.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don = #1.
        /// </summary>
        public static string Criterion_AlignmentFeat_Equal {
            get {
                return ResourceManager.GetString("Criterion.AlignmentFeat.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don #1 = #2.
        /// </summary>
        public static string Criterion_AlignmentFeat_Equal_Level {
            get {
                return ResourceManager.GetString("Criterion.AlignmentFeat.Equal.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don &lt; #1.
        /// </summary>
        public static string Criterion_AlignmentFeat_Inferior {
            get {
                return ResourceManager.GetString("Criterion.AlignmentFeat.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don #1 &lt; #2.
        /// </summary>
        public static string Criterion_AlignmentFeat_Inferior_Level {
            get {
                return ResourceManager.GetString("Criterion.AlignmentFeat.Inferior.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don &gt; #1.
        /// </summary>
        public static string Criterion_AlignmentFeat_Superior {
            get {
                return ResourceManager.GetString("Criterion.AlignmentFeat.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don #1 &gt; #2.
        /// </summary>
        public static string Criterion_AlignmentFeat_Superior_Level {
            get {
                return ResourceManager.GetString("Criterion.AlignmentFeat.Superior.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau d&apos;alignement ≠ #1.
        /// </summary>
        public static string Criterion_AlignmentLevel_Different {
            get {
                return ResourceManager.GetString("Criterion.AlignmentLevel.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau d&apos;alignement = #1.
        /// </summary>
        public static string Criterion_AlignmentLevel_Equal {
            get {
                return ResourceManager.GetString("Criterion.AlignmentLevel.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau d&apos;alignement &lt; #1.
        /// </summary>
        public static string Criterion_AlignmentLevel_Inferior {
            get {
                return ResourceManager.GetString("Criterion.AlignmentLevel.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau d&apos;alignement &gt; #1.
        /// </summary>
        public static string Criterion_AlignmentLevel_Superior {
            get {
                return ResourceManager.GetString("Criterion.AlignmentLevel.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade ≠ #1.
        /// </summary>
        public static string Criterion_AlignmentRank_Different {
            get {
                return ResourceManager.GetString("Criterion.AlignmentRank.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade = #1.
        /// </summary>
        public static string Criterion_AlignmentRank_Equal {
            get {
                return ResourceManager.GetString("Criterion.AlignmentRank.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade &lt; #1.
        /// </summary>
        public static string Criterion_AlignmentRank_Inferior {
            get {
                return ResourceManager.GetString("Criterion.AlignmentRank.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade &gt; #1.
        /// </summary>
        public static string Criterion_AlignmentRank_Superior {
            get {
                return ResourceManager.GetString("Criterion.AlignmentRank.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spécialisation ≠ #1.
        /// </summary>
        public static string Criterion_AlignmentSpecialization_Different {
            get {
                return ResourceManager.GetString("Criterion.AlignmentSpecialization.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spécialisation = #1.
        /// </summary>
        public static string Criterion_AlignmentSpecialization_Equal {
            get {
                return ResourceManager.GetString("Criterion.AlignmentSpecialization.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et.
        /// </summary>
        public static string Criterion_And {
            get {
                return ResourceManager.GetString("Criterion.And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créature invocable disponible ≠ #1.
        /// </summary>
        public static string Criterion_AvailableSummon_Different {
            get {
                return ResourceManager.GetString("Criterion.AvailableSummon.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créature invocable disponible = #1.
        /// </summary>
        public static string Criterion_AvailableSummon_Equal {
            get {
                return ResourceManager.GetString("Criterion.AvailableSummon.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créature invocable disponible &lt; #1.
        /// </summary>
        public static string Criterion_AvailableSummon_Inferior {
            get {
                return ResourceManager.GetString("Criterion.AvailableSummon.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créature invocable disponible &gt; #1.
        /// </summary>
        public static string Criterion_AvailableSummon_Superior {
            get {
                return ResourceManager.GetString("Criterion.AvailableSummon.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité de base ≠ #1.
        /// </summary>
        public static string Criterion_BaseAgility_Different {
            get {
                return ResourceManager.GetString("Criterion.BaseAgility.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité de base = #1.
        /// </summary>
        public static string Criterion_BaseAgility_Equal {
            get {
                return ResourceManager.GetString("Criterion.BaseAgility.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité de base &lt; #1.
        /// </summary>
        public static string Criterion_BaseAgility_Inferior {
            get {
                return ResourceManager.GetString("Criterion.BaseAgility.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité de base &gt; #1.
        /// </summary>
        public static string Criterion_BaseAgility_Superior {
            get {
                return ResourceManager.GetString("Criterion.BaseAgility.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance de base ≠ #1.
        /// </summary>
        public static string Criterion_BaseChance_Different {
            get {
                return ResourceManager.GetString("Criterion.BaseChance.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance de base = #1.
        /// </summary>
        public static string Criterion_BaseChance_Equal {
            get {
                return ResourceManager.GetString("Criterion.BaseChance.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance de base &lt; #1.
        /// </summary>
        public static string Criterion_BaseChance_Inferior {
            get {
                return ResourceManager.GetString("Criterion.BaseChance.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance de base &gt; #1.
        /// </summary>
        public static string Criterion_BaseChance_Superior {
            get {
                return ResourceManager.GetString("Criterion.BaseChance.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence de base ≠ #1.
        /// </summary>
        public static string Criterion_BaseIntelligence_Different {
            get {
                return ResourceManager.GetString("Criterion.BaseIntelligence.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence de base = #1.
        /// </summary>
        public static string Criterion_BaseIntelligence_Equal {
            get {
                return ResourceManager.GetString("Criterion.BaseIntelligence.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence de base &lt; #1.
        /// </summary>
        public static string Criterion_BaseIntelligence_Inferior {
            get {
                return ResourceManager.GetString("Criterion.BaseIntelligence.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence de base &gt; #1.
        /// </summary>
        public static string Criterion_BaseIntelligence_Superior {
            get {
                return ResourceManager.GetString("Criterion.BaseIntelligence.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force de base ≠ #1.
        /// </summary>
        public static string Criterion_BaseStrength_Different {
            get {
                return ResourceManager.GetString("Criterion.BaseStrength.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force de base = #1.
        /// </summary>
        public static string Criterion_BaseStrength_Equal {
            get {
                return ResourceManager.GetString("Criterion.BaseStrength.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force de base &lt; #1.
        /// </summary>
        public static string Criterion_BaseStrength_Inferior {
            get {
                return ResourceManager.GetString("Criterion.BaseStrength.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force de base &gt; #1.
        /// </summary>
        public static string Criterion_BaseStrength_Superior {
            get {
                return ResourceManager.GetString("Criterion.BaseStrength.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité de base ≠ #1.
        /// </summary>
        public static string Criterion_BaseVitality_Different {
            get {
                return ResourceManager.GetString("Criterion.BaseVitality.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité de base = #1.
        /// </summary>
        public static string Criterion_BaseVitality_Equal {
            get {
                return ResourceManager.GetString("Criterion.BaseVitality.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité de base &lt; #1.
        /// </summary>
        public static string Criterion_BaseVitality_Inferior {
            get {
                return ResourceManager.GetString("Criterion.BaseVitality.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité de base &gt; #1.
        /// </summary>
        public static string Criterion_BaseVitality_Superior {
            get {
                return ResourceManager.GetString("Criterion.BaseVitality.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagesse de base ≠ #1.
        /// </summary>
        public static string Criterion_BaseWisdom_Different {
            get {
                return ResourceManager.GetString("Criterion.BaseWisdom.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagesse de base = #1.
        /// </summary>
        public static string Criterion_BaseWisdom_Equal {
            get {
                return ResourceManager.GetString("Criterion.BaseWisdom.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagesse de base &lt; #1.
        /// </summary>
        public static string Criterion_BaseWisdom_Inferior {
            get {
                return ResourceManager.GetString("Criterion.BaseWisdom.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagesse de base &gt; #1.
        /// </summary>
        public static string Criterion_BaseWisdom_Superior {
            get {
                return ResourceManager.GetString("Criterion.BaseWisdom.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meilleur élément ≠ #1.
        /// </summary>
        public static string Criterion_BestElement_Different {
            get {
                return ResourceManager.GetString("Criterion.BestElement.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meilleur élément = #1.
        /// </summary>
        public static string Criterion_BestElement_Equal {
            get {
                return ResourceManager.GetString("Criterion.BestElement.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe ≠ #1.
        /// </summary>
        public static string Criterion_Breed_Different {
            get {
                return ResourceManager.GetString("Criterion.Breed.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe = #1.
        /// </summary>
        public static string Criterion_Breed_Equal {
            get {
                return ResourceManager.GetString("Criterion.Breed.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main ≠ #1.
        /// </summary>
        public static string Criterion_CardCombination_Different {
            get {
                return ResourceManager.GetString("Criterion.CardCombination.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main = #1.
        /// </summary>
        public static string Criterion_CardCombination_Equal {
            get {
                return ResourceManager.GetString("Criterion.CardCombination.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance ≠ #1.
        /// </summary>
        public static string Criterion_Chance_Different {
            get {
                return ResourceManager.GetString("Criterion.Chance.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance = #1.
        /// </summary>
        public static string Criterion_Chance_Equal {
            get {
                return ResourceManager.GetString("Criterion.Chance.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance &lt; #1.
        /// </summary>
        public static string Criterion_Chance_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Chance.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance &gt; #1.
        /// </summary>
        public static string Criterion_Chance_Superior {
            get {
                return ResourceManager.GetString("Criterion.Chance.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA ≠ #1.
        /// </summary>
        public static string Criterion_CurrentActionPoint_Different {
            get {
                return ResourceManager.GetString("Criterion.CurrentActionPoint.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA = #1.
        /// </summary>
        public static string Criterion_CurrentActionPoint_Equal {
            get {
                return ResourceManager.GetString("Criterion.CurrentActionPoint.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA &lt; #1.
        /// </summary>
        public static string Criterion_CurrentActionPoint_Inferior {
            get {
                return ResourceManager.GetString("Criterion.CurrentActionPoint.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA &gt; #1.
        /// </summary>
        public static string Criterion_CurrentActionPoint_Superior {
            get {
                return ResourceManager.GetString("Criterion.CurrentActionPoint.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM ≠ #1.
        /// </summary>
        public static string Criterion_CurrentMovementPoint_Different {
            get {
                return ResourceManager.GetString("Criterion.CurrentMovementPoint.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM = #1.
        /// </summary>
        public static string Criterion_CurrentMovementPoint_Equal {
            get {
                return ResourceManager.GetString("Criterion.CurrentMovementPoint.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM &lt; #1.
        /// </summary>
        public static string Criterion_CurrentMovementPoint_Inferior {
            get {
                return ResourceManager.GetString("Criterion.CurrentMovementPoint.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM &gt; #1.
        /// </summary>
        public static string Criterion_CurrentMovementPoint_Superior {
            get {
                return ResourceManager.GetString("Criterion.CurrentMovementPoint.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points de déshonneur ≠ #1.
        /// </summary>
        public static string Criterion_DisgracePoint_Different {
            get {
                return ResourceManager.GetString("Criterion.DisgracePoint.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points de déshonneur = #1.
        /// </summary>
        public static string Criterion_DisgracePoint_Equal {
            get {
                return ResourceManager.GetString("Criterion.DisgracePoint.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points de déshonneur &lt; #1.
        /// </summary>
        public static string Criterion_DisgracePoint_Inferior {
            get {
                return ResourceManager.GetString("Criterion.DisgracePoint.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points de déshonneur &gt; #1.
        /// </summary>
        public static string Criterion_DisgracePoint_Superior {
            get {
                return ResourceManager.GetString("Criterion.DisgracePoint.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pas connaître l&apos;attitude #1.
        /// </summary>
        public static string Criterion_Emote_Different {
            get {
                return ResourceManager.GetString("Criterion.Emote.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connaître l&apos;attitude #1.
        /// </summary>
        public static string Criterion_Emote_Equal {
            get {
                return ResourceManager.GetString("Criterion.Emote.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pods libre ≠ #1.
        /// </summary>
        public static string Criterion_FreeWeight_Different {
            get {
                return ResourceManager.GetString("Criterion.FreeWeight.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pods libre = #1.
        /// </summary>
        public static string Criterion_FreeWeight_Equal {
            get {
                return ResourceManager.GetString("Criterion.FreeWeight.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pods libre &lt; #1.
        /// </summary>
        public static string Criterion_FreeWeight_Inferior {
            get {
                return ResourceManager.GetString("Criterion.FreeWeight.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pods libre &gt; #1.
        /// </summary>
        public static string Criterion_FreeWeight_Superior {
            get {
                return ResourceManager.GetString("Criterion.FreeWeight.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexe ≠ #1.
        /// </summary>
        public static string Criterion_Gender_Different {
            get {
                return ResourceManager.GetString("Criterion.Gender.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexe = #1.
        /// </summary>
        public static string Criterion_Gender_Equal {
            get {
                return ResourceManager.GetString("Criterion.Gender.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pas être propriétaire d&apos;une maison.
        /// </summary>
        public static string Criterion_Homeowner_Equal_False {
            get {
                return ResourceManager.GetString("Criterion.Homeowner.Equal.False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etre propriétaire d&apos;une maison.
        /// </summary>
        public static string Criterion_Homeowner_Equal_True {
            get {
                return ResourceManager.GetString("Criterion.Homeowner.Equal.True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points d&apos;honneur ≠ #1.
        /// </summary>
        public static string Criterion_HonorPoint_Different {
            get {
                return ResourceManager.GetString("Criterion.HonorPoint.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points d&apos;honneur = #1.
        /// </summary>
        public static string Criterion_HonorPoint_Equal {
            get {
                return ResourceManager.GetString("Criterion.HonorPoint.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points d&apos;honneur &lt; #1.
        /// </summary>
        public static string Criterion_HonorPoint_Inferior {
            get {
                return ResourceManager.GetString("Criterion.HonorPoint.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points d&apos;honneur &gt; #1.
        /// </summary>
        public static string Criterion_HonorPoint_Superior {
            get {
                return ResourceManager.GetString("Criterion.HonorPoint.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence ≠ #1.
        /// </summary>
        public static string Criterion_Intelligence_Different {
            get {
                return ResourceManager.GetString("Criterion.Intelligence.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence = #1.
        /// </summary>
        public static string Criterion_Intelligence_Equal {
            get {
                return ResourceManager.GetString("Criterion.Intelligence.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence &lt; #1.
        /// </summary>
        public static string Criterion_Intelligence_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Intelligence.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence &gt; #1.
        /// </summary>
        public static string Criterion_Intelligence_Superior {
            get {
                return ResourceManager.GetString("Criterion.Intelligence.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pas posséder l&apos;objet #1.
        /// </summary>
        public static string Criterion_Item_Different {
            get {
                return ResourceManager.GetString("Criterion.Item.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoir équipé l&apos;objet #1.
        /// </summary>
        public static string Criterion_Item_E {
            get {
                return ResourceManager.GetString("Criterion.Item.E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posséder l&apos;objet #1.
        /// </summary>
        public static string Criterion_Item_Equal {
            get {
                return ResourceManager.GetString("Criterion.Item.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pas avoir équipé l&apos;objet #1.
        /// </summary>
        public static string Criterion_Item_X {
            get {
                return ResourceManager.GetString("Criterion.Item.X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métier ≠ #1.
        /// </summary>
        public static string Criterion_Job_Different {
            get {
                return ResourceManager.GetString("Criterion.Job.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métier #1 ≠ #2.
        /// </summary>
        public static string Criterion_Job_Different_Level {
            get {
                return ResourceManager.GetString("Criterion.Job.Different.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métier = #1.
        /// </summary>
        public static string Criterion_Job_Equal {
            get {
                return ResourceManager.GetString("Criterion.Job.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métier #1 = #2.
        /// </summary>
        public static string Criterion_Job_Equal_Level {
            get {
                return ResourceManager.GetString("Criterion.Job.Equal.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métier &lt; #1.
        /// </summary>
        public static string Criterion_Job_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Job.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métier #1 &lt; #2.
        /// </summary>
        public static string Criterion_Job_Inferior_Level {
            get {
                return ResourceManager.GetString("Criterion.Job.Inferior.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métier &gt; #1.
        /// </summary>
        public static string Criterion_Job_Superior {
            get {
                return ResourceManager.GetString("Criterion.Job.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métier #1 &gt; #2.
        /// </summary>
        public static string Criterion_Job_Superior_Level {
            get {
                return ResourceManager.GetString("Criterion.Job.Superior.Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamas ≠ #1.
        /// </summary>
        public static string Criterion_Kamas_Different {
            get {
                return ResourceManager.GetString("Criterion.Kamas.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamas = #1.
        /// </summary>
        public static string Criterion_Kamas_Equal {
            get {
                return ResourceManager.GetString("Criterion.Kamas.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamas &lt; #1.
        /// </summary>
        public static string Criterion_Kamas_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Kamas.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamas &gt; #1.
        /// </summary>
        public static string Criterion_Kamas_Superior {
            get {
                return ResourceManager.GetString("Criterion.Kamas.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau ≠ #1.
        /// </summary>
        public static string Criterion_Level_Different {
            get {
                return ResourceManager.GetString("Criterion.Level.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau = #1.
        /// </summary>
        public static string Criterion_Level_Equal {
            get {
                return ResourceManager.GetString("Criterion.Level.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau &lt; #1.
        /// </summary>
        public static string Criterion_Level_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Level.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau &gt; #1.
        /// </summary>
        public static string Criterion_Level_Superior {
            get {
                return ResourceManager.GetString("Criterion.Level.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparence ≠ #1.
        /// </summary>
        public static string Criterion_Look_Different {
            get {
                return ResourceManager.GetString("Criterion.Look.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparence = #1.
        /// </summary>
        public static string Criterion_Look_Equal {
            get {
                return ResourceManager.GetString("Criterion.Look.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pas être sur la map #1 (#2).
        /// </summary>
        public static string Criterion_Map_Different {
            get {
                return ResourceManager.GetString("Criterion.Map.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etre sur la map #1 (#2).
        /// </summary>
        public static string Criterion_Map_Equal {
            get {
                return ResourceManager.GetString("Criterion.Map.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de joueurs sur la map #1 (#2) ≠ #3.
        /// </summary>
        public static string Criterion_MapPlayer_Different {
            get {
                return ResourceManager.GetString("Criterion.MapPlayer.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de joueurs sur la map #1 (#2) = #3.
        /// </summary>
        public static string Criterion_MapPlayer_Equal {
            get {
                return ResourceManager.GetString("Criterion.MapPlayer.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de joueurs sur la map #1 (#2) &lt; #3.
        /// </summary>
        public static string Criterion_MapPlayer_Inferior {
            get {
                return ResourceManager.GetString("Criterion.MapPlayer.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de joueurs sur la map #1 (#2) &gt; #3.
        /// </summary>
        public static string Criterion_MapPlayer_Superior {
            get {
                return ResourceManager.GetString("Criterion.MapPlayer.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-zone ≠ #1.
        /// </summary>
        public static string Criterion_MapSubArea_Different {
            get {
                return ResourceManager.GetString("Criterion.MapSubArea.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-zone = #1.
        /// </summary>
        public static string Criterion_MapSubArea_Equal {
            get {
                return ResourceManager.GetString("Criterion.MapSubArea.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etre #1.
        /// </summary>
        public static string Criterion_MaritalStatus_Equal {
            get {
                return ResourceManager.GetString("Criterion.MaritalStatus.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute ≠ #1.
        /// </summary>
        public static string Criterion_Minute_Different {
            get {
                return ResourceManager.GetString("Criterion.Minute.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute = #1.
        /// </summary>
        public static string Criterion_Minute_Equal {
            get {
                return ResourceManager.GetString("Criterion.Minute.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute &lt; #1.
        /// </summary>
        public static string Criterion_Minute_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Minute.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute &gt; #1.
        /// </summary>
        public static string Criterion_Minute_Superior {
            get {
                return ResourceManager.GetString("Criterion.Minute.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le monstre #1 n&apos;est pas invoqué dans l&apos;équipe alliée.
        /// </summary>
        public static string Criterion_MonsterSummon_Different {
            get {
                return ResourceManager.GetString("Criterion.MonsterSummon.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le monstre #1 est invoqué dans l&apos;équipe alliée.
        /// </summary>
        public static string Criterion_MonsterSummon_Equal {
            get {
                return ResourceManager.GetString("Criterion.MonsterSummon.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM ≠ #1.
        /// </summary>
        public static string Criterion_MovementPoint_Different {
            get {
                return ResourceManager.GetString("Criterion.MovementPoint.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM = #1.
        /// </summary>
        public static string Criterion_MovementPoint_Equal {
            get {
                return ResourceManager.GetString("Criterion.MovementPoint.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM &lt; #1.
        /// </summary>
        public static string Criterion_MovementPoint_Inferior {
            get {
                return ResourceManager.GetString("Criterion.MovementPoint.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM &gt; #1.
        /// </summary>
        public static string Criterion_MovementPoint_Superior {
            get {
                return ResourceManager.GetString("Criterion.MovementPoint.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom ≠ #1.
        /// </summary>
        public static string Criterion_Name_Different {
            get {
                return ResourceManager.GetString("Criterion.Name.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom = #1.
        /// </summary>
        public static string Criterion_Name_Equal {
            get {
                return ResourceManager.GetString("Criterion.Name.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom ≈ #1.
        /// </summary>
        public static string Criterion_Name_SoftEqual {
            get {
                return ResourceManager.GetString("Criterion.Name.SoftEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ou.
        /// </summary>
        public static string Criterion_Or {
            get {
                return ResourceManager.GetString("Criterion.Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité ≠ #1%.
        /// </summary>
        public static string Criterion_PercentVitality_Different {
            get {
                return ResourceManager.GetString("Criterion.PercentVitality.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité = #1%.
        /// </summary>
        public static string Criterion_PercentVitality_Equal {
            get {
                return ResourceManager.GetString("Criterion.PercentVitality.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité &lt; #1%.
        /// </summary>
        public static string Criterion_PercentVitality_Inferior {
            get {
                return ResourceManager.GetString("Criterion.PercentVitality.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité &gt; #1%.
        /// </summary>
        public static string Criterion_PercentVitality_Superior {
            get {
                return ResourceManager.GetString("Criterion.PercentVitality.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau admin ≠ #1.
        /// </summary>
        public static string Criterion_PlayerRights_Different {
            get {
                return ResourceManager.GetString("Criterion.PlayerRights.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau admin = #1.
        /// </summary>
        public static string Criterion_PlayerRights_Equal {
            get {
                return ResourceManager.GetString("Criterion.PlayerRights.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau admin &lt; #1.
        /// </summary>
        public static string Criterion_PlayerRights_Inferior {
            get {
                return ResourceManager.GetString("Criterion.PlayerRights.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau admin &gt; #1.
        /// </summary>
        public static string Criterion_PlayerRights_Superior {
            get {
                return ResourceManager.GetString("Criterion.PlayerRights.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quête #1 pas en cours.
        /// </summary>
        public static string Criterion_Quest_Different {
            get {
                return ResourceManager.GetString("Criterion.Quest.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quête #1 en cours.
        /// </summary>
        public static string Criterion_Quest_Equal {
            get {
                return ResourceManager.GetString("Criterion.Quest.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quête #1 non validée.
        /// </summary>
        public static string Criterion_Quest_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Quest.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quête #1 validée.
        /// </summary>
        public static string Criterion_Quest_Superior {
            get {
                return ResourceManager.GetString("Criterion.Quest.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectif de quête #1 pas en cours.
        /// </summary>
        public static string Criterion_QuestObjective_Different {
            get {
                return ResourceManager.GetString("Criterion.QuestObjective.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectif de quête #1 en cours.
        /// </summary>
        public static string Criterion_QuestObjective_Equal {
            get {
                return ResourceManager.GetString("Criterion.QuestObjective.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectif de quête #1 non validé.
        /// </summary>
        public static string Criterion_QuestObjective_Inferior {
            get {
                return ResourceManager.GetString("Criterion.QuestObjective.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectif de quête #1 validé.
        /// </summary>
        public static string Criterion_QuestObjective_Superior {
            get {
                return ResourceManager.GetString("Criterion.QuestObjective.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape de quête #1 pas en cours.
        /// </summary>
        public static string Criterion_QuestStep_Different {
            get {
                return ResourceManager.GetString("Criterion.QuestStep.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape de quête #1 en cours.
        /// </summary>
        public static string Criterion_QuestStep_Equal {
            get {
                return ResourceManager.GetString("Criterion.QuestStep.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape de quête #1 non validée.
        /// </summary>
        public static string Criterion_QuestStep_Inferior {
            get {
                return ResourceManager.GetString("Criterion.QuestStep.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape de quête #1 validée.
        /// </summary>
        public static string Criterion_QuestStep_Superior {
            get {
                return ResourceManager.GetString("Criterion.QuestStep.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pas être sur le serveur #1.
        /// </summary>
        public static string Criterion_Server_Different {
            get {
                return ResourceManager.GetString("Criterion.Server.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etre sur le serveur #1.
        /// </summary>
        public static string Criterion_Server_Equal {
            get {
                return ResourceManager.GetString("Criterion.Server.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu n°#1 désactivé.
        /// </summary>
        public static string Criterion_ServerContent_Different {
            get {
                return ResourceManager.GetString("Criterion.ServerContent.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu n°#1 activé.
        /// </summary>
        public static string Criterion_ServerContent_Equal {
            get {
                return ResourceManager.GetString("Criterion.ServerContent.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement #1 libre.
        /// </summary>
        public static string Criterion_Slot_Different {
            get {
                return ResourceManager.GetString("Criterion.Slot.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement #1 occupé.
        /// </summary>
        public static string Criterion_Slot_Equal {
            get {
                return ResourceManager.GetString("Criterion.Slot.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pas être dans l&apos;état #1.
        /// </summary>
        public static string Criterion_State_Different {
            get {
                return ResourceManager.GetString("Criterion.State.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etre dans l&apos;état #1.
        /// </summary>
        public static string Criterion_State_Equal {
            get {
                return ResourceManager.GetString("Criterion.State.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force ≠ #1.
        /// </summary>
        public static string Criterion_Strength_Different {
            get {
                return ResourceManager.GetString("Criterion.Strength.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force = #1.
        /// </summary>
        public static string Criterion_Strength_Equal {
            get {
                return ResourceManager.GetString("Criterion.Strength.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force &lt; #1.
        /// </summary>
        public static string Criterion_Strength_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Strength.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force &gt; #1.
        /// </summary>
        public static string Criterion_Strength_Superior {
            get {
                return ResourceManager.GetString("Criterion.Strength.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pas être abonné.
        /// </summary>
        public static string Criterion_Subscribe_Equal_False {
            get {
                return ResourceManager.GetString("Criterion.Subscribe.Equal.False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etre abonné.
        /// </summary>
        public static string Criterion_Subscribe_Equal_True {
            get {
                return ResourceManager.GetString("Criterion.Subscribe.Equal.True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour ≠ #1.
        /// </summary>
        public static string Criterion_Turn_Different {
            get {
                return ResourceManager.GetString("Criterion.Turn.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour = #1.
        /// </summary>
        public static string Criterion_Turn_Equal {
            get {
                return ResourceManager.GetString("Criterion.Turn.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour pair.
        /// </summary>
        public static string Criterion_Turn_Even {
            get {
                return ResourceManager.GetString("Criterion.Turn.Even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour &lt; #1.
        /// </summary>
        public static string Criterion_Turn_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Turn.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour impair.
        /// </summary>
        public static string Criterion_Turn_Odd {
            get {
                return ResourceManager.GetString("Criterion.Turn.Odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour &gt; #1.
        /// </summary>
        public static string Criterion_Turn_Superior {
            get {
                return ResourceManager.GetString("Criterion.Turn.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inutilisable.
        /// </summary>
        public static string Criterion_UnusableItem_Equal {
            get {
                return ResourceManager.GetString("Criterion.UnusableItem.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité ≠ #1.
        /// </summary>
        public static string Criterion_Vitality_Different {
            get {
                return ResourceManager.GetString("Criterion.Vitality.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité = #1.
        /// </summary>
        public static string Criterion_Vitality_Equal {
            get {
                return ResourceManager.GetString("Criterion.Vitality.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité &lt; #1.
        /// </summary>
        public static string Criterion_Vitality_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Vitality.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalité &gt; #1.
        /// </summary>
        public static string Criterion_Vitality_Superior {
            get {
                return ResourceManager.GetString("Criterion.Vitality.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagesse ≠ #1.
        /// </summary>
        public static string Criterion_Wisdom_Different {
            get {
                return ResourceManager.GetString("Criterion.Wisdom.Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagesse = #1.
        /// </summary>
        public static string Criterion_Wisdom_Equal {
            get {
                return ResourceManager.GetString("Criterion.Wisdom.Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagesse &lt; #1.
        /// </summary>
        public static string Criterion_Wisdom_Inferior {
            get {
                return ResourceManager.GetString("Criterion.Wisdom.Inferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagesse &gt; #1.
        /// </summary>
        public static string Criterion_Wisdom_Superior {
            get {
                return ResourceManager.GetString("Criterion.Wisdom.Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lié au compte.
        /// </summary>
        public static string Effect_LinkedToAccount {
            get {
                return ResourceManager.GetString("Effect.LinkedToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dans #1% des cas.
        /// </summary>
        public static string Effect_Probability {
            get {
                return ResourceManager.GetString("Effect.Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 tour(s).
        /// </summary>
        public static string Effect_Turn {
            get {
                return ResourceManager.GetString("Effect.Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effet #1 inconnu non référencé (#2).
        /// </summary>
        public static string Effect_Unknown {
            get {
                return ResourceManager.GetString("Effect.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croix.
        /// </summary>
        public static string EffectArea_1 {
            get {
                return ResourceManager.GetString("EffectArea.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone.
        /// </summary>
        public static string EffectArea_10 {
            get {
                return ResourceManager.GetString("EffectArea.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croix diagonale.
        /// </summary>
        public static string EffectArea_11 {
            get {
                return ResourceManager.GetString("EffectArea.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En T.
        /// </summary>
        public static string EffectArea_12 {
            get {
                return ResourceManager.GetString("EffectArea.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En T.
        /// </summary>
        public static string EffectArea_13 {
            get {
                return ResourceManager.GetString("EffectArea.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu (14).
        /// </summary>
        public static string EffectArea_14 {
            get {
                return ResourceManager.GetString("EffectArea.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croix vide.
        /// </summary>
        public static string EffectArea_15 {
            get {
                return ResourceManager.GetString("EffectArea.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne large.
        /// </summary>
        public static string EffectArea_16 {
            get {
                return ResourceManager.GetString("EffectArea.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointe.
        /// </summary>
        public static string EffectArea_17 {
            get {
                return ResourceManager.GetString("EffectArea.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne perpendiculaire.
        /// </summary>
        public static string EffectArea_2 {
            get {
                return ResourceManager.GetString("EffectArea.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etoile.
        /// </summary>
        public static string EffectArea_21 {
            get {
                return ResourceManager.GetString("EffectArea.21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu (22).
        /// </summary>
        public static string EffectArea_22 {
            get {
                return ResourceManager.GetString("EffectArea.22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourche.
        /// </summary>
        public static string EffectArea_23 {
            get {
                return ResourceManager.GetString("EffectArea.23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cercle.
        /// </summary>
        public static string EffectArea_3 {
            get {
                return ResourceManager.GetString("EffectArea.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string EffectArea_4 {
            get {
                return ResourceManager.GetString("EffectArea.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne.
        /// </summary>
        public static string EffectArea_5 {
            get {
                return ResourceManager.GetString("EffectArea.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damier.
        /// </summary>
        public static string EffectArea_6 {
            get {
                return ResourceManager.GetString("EffectArea.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cercle.
        /// </summary>
        public static string EffectArea_67 {
            get {
                return ResourceManager.GetString("EffectArea.67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damier.
        /// </summary>
        public static string EffectArea_68 {
            get {
                return ResourceManager.GetString("EffectArea.68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anneau.
        /// </summary>
        public static string EffectArea_7 {
            get {
                return ResourceManager.GetString("EffectArea.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne.
        /// </summary>
        public static string EffectArea_76 {
            get {
                return ResourceManager.GetString("EffectArea.76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anneau.
        /// </summary>
        public static string EffectArea_79 {
            get {
                return ResourceManager.GetString("EffectArea.79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carré.
        /// </summary>
        public static string EffectArea_8 {
            get {
                return ResourceManager.GetString("EffectArea.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string EffectArea_80 {
            get {
                return ResourceManager.GetString("EffectArea.80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne perpendiculaire.
        /// </summary>
        public static string EffectArea_84 {
            get {
                return ResourceManager.GetString("EffectArea.84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croix.
        /// </summary>
        public static string EffectArea_88 {
            get {
                return ResourceManager.GetString("EffectArea.88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carré vide.
        /// </summary>
        public static string EffectArea_9 {
            get {
                return ResourceManager.GetString("EffectArea.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité.
        /// </summary>
        public static string Element_Agility {
            get {
                return ResourceManager.GetString("Element.Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        public static string Element_Chance {
            get {
                return ResourceManager.GetString("Element.Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string Element_Intelligence {
            get {
                return ResourceManager.GetString("Element.Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutre.
        /// </summary>
        public static string Element_Neutral {
            get {
                return ResourceManager.GetString("Element.Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        public static string Element_Strength {
            get {
                return ResourceManager.GetString("Element.Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femme.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender.Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homme.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender.Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanceur, check lanceur.
        /// </summary>
        public static string GiveItemTarget_CasterCheckCaster {
            get {
                return ResourceManager.GetString("GiveItemTarget.CasterCheckCaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanceur, check cible.
        /// </summary>
        public static string GiveItemTarget_CasterCheckTarget {
            get {
                return ResourceManager.GetString("GiveItemTarget.CasterCheckTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cible, check cible.
        /// </summary>
        public static string GiveItemTarget_TargetCheckTarget {
            get {
                return ResourceManager.GetString("GiveItemTarget.TargetCheckTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclos.
        /// </summary>
        public static string GuildStructure_Enclosure {
            get {
                return ResourceManager.GetString("GuildStructure.Enclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maison.
        /// </summary>
        public static string GuildStructure_House {
            get {
                return ResourceManager.GetString("GuildStructure.House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure inconnu.
        /// </summary>
        public static string GuildStructure_None {
            get {
                return ResourceManager.GetString("GuildStructure.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stérile.
        /// </summary>
        public static string Infertile {
            get {
                return ResourceManager.GetString("Infertile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inf..
        /// </summary>
        public static string Infinity {
            get {
                return ResourceManager.GetString("Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string LastMeal_None {
            get {
                return ResourceManager.GetString("LastMeal.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marié(e).
        /// </summary>
        public static string MaritalStatus_Married {
            get {
                return ResourceManager.GetString("MaritalStatus.Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Célibataire.
        /// </summary>
        public static string MaritalStatus_Single {
            get {
                return ResourceManager.GetString("MaritalStatus.Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;objectif #1 inconnu non référencé (#2).
        /// </summary>
        public static string QuestObjectiveType_Unknown {
            get {
                return ResourceManager.GetString("QuestObjectiveType.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune #1.
        /// </summary>
        public static string Rune {
            get {
                return ResourceManager.GetString("Rune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe.
        /// </summary>
        public static string SpellCategory_Breed {
            get {
                return ResourceManager.GetString("SpellCategory.Breed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elémentaire.
        /// </summary>
        public static string SpellCategory_Elementary {
            get {
                return ResourceManager.GetString("SpellCategory.Elementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evenement.
        /// </summary>
        public static string SpellCategory_Event {
            get {
                return ResourceManager.GetString("SpellCategory.Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fée d&apos;artifice.
        /// </summary>
        public static string SpellCategory_Fairywork {
            get {
                return ResourceManager.GetString("SpellCategory.Fairywork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        public static string SpellCategory_None {
            get {
                return ResourceManager.GetString("SpellCategory.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percepteur.
        /// </summary>
        public static string SpellCategory_Perceptor {
            get {
                return ResourceManager.GetString("SpellCategory.Perceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spécial.
        /// </summary>
        public static string SpellCategory_Special {
            get {
                return ResourceManager.GetString("SpellCategory.Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation.
        /// </summary>
        public static string SpellCategory_Summon {
            get {
                return ResourceManager.GetString("SpellCategory.Summon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe - Temporis.
        /// </summary>
        public static string SpellCategory_TemporisBreed {
            get {
                return ResourceManager.GetString("SpellCategory.TemporisBreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commun - Temporis.
        /// </summary>
        public static string SpellCategory_TemporisCommon {
            get {
                return ResourceManager.GetString("SpellCategory.TemporisCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic - Temporis.
        /// </summary>
        public static string SpellCategory_TemporisEpic {
            get {
                return ResourceManager.GetString("SpellCategory.TemporisEpic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendaire - Temporis.
        /// </summary>
        public static string SpellCategory_TemporisLegendary {
            get {
                return ResourceManager.GetString("SpellCategory.TemporisLegendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monstre - Temporis.
        /// </summary>
        public static string SpellCategory_TemporisMonster {
            get {
                return ResourceManager.GetString("SpellCategory.TemporisMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare - Temporis.
        /// </summary>
        public static string SpellCategory_TemporisRare {
            get {
                return ResourceManager.GetString("SpellCategory.TemporisRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort déclenché - Temporis.
        /// </summary>
        public static string SpellCategory_TemporisTriggeredSpell {
            get {
                return ResourceManager.GetString("SpellCategory.TemporisTriggeredSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maîtrise.
        /// </summary>
        public static string SpellCategory_WeaponSkill {
            get {
                return ResourceManager.GetString("SpellCategory.WeaponSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classe.
        /// </summary>
        public static string SpellLevelCategory_Breed {
            get {
                return ResourceManager.GetString("SpellLevelCategory.Breed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elémentaire.
        /// </summary>
        public static string SpellLevelCategory_Elementary {
            get {
                return ResourceManager.GetString("SpellLevelCategory.Elementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spécial.
        /// </summary>
        public static string SpellLevelCategory_Special {
            get {
                return ResourceManager.GetString("SpellLevelCategory.Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation.
        /// </summary>
        public static string SpellLevelCategory_Summon {
            get {
                return ResourceManager.GetString("SpellLevelCategory.Summon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maîtrise.
        /// </summary>
        public static string SpellLevelCategory_WeaponSkill {
            get {
                return ResourceManager.GetString("SpellLevelCategory.WeaponSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft.
        /// </summary>
        public static string SpellOrigin_Craft {
            get {
                return ResourceManager.GetString("SpellOrigin.Craft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        public static string SpellOrigin_Drop {
            get {
                return ResourceManager.GetString("SpellOrigin.Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        public static string SpellOrigin_None {
            get {
                return ResourceManager.GetString("SpellOrigin.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        public static string SpellOrigin_Unknown {
            get {
                return ResourceManager.GetString("SpellOrigin.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité.
        /// </summary>
        public static string SpellType_Agility {
            get {
                return ResourceManager.GetString("SpellType.Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        public static string SpellType_Chance {
            get {
                return ResourceManager.GetString("SpellType.Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soin.
        /// </summary>
        public static string SpellType_Heal {
            get {
                return ResourceManager.GetString("SpellType.Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string SpellType_Intelligence {
            get {
                return ResourceManager.GetString("SpellType.Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-élément.
        /// </summary>
        public static string SpellType_MultiElement {
            get {
                return ResourceManager.GetString("SpellType.MultiElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutre.
        /// </summary>
        public static string SpellType_Neutral {
            get {
                return ResourceManager.GetString("SpellType.Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string SpellType_None {
            get {
                return ResourceManager.GetString("SpellType.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        public static string SpellType_Strength {
            get {
                return ResourceManager.GetString("SpellType.Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocation.
        /// </summary>
        public static string SpellType_Summon {
            get {
                return ResourceManager.GetString("SpellType.Summon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilitaire.
        /// </summary>
        public static string SpellType_Utility {
            get {
                return ResourceManager.GetString("SpellType.Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commune.
        /// </summary>
        public static string TTGCardRarity_Common {
            get {
                return ResourceManager.GetString("TTGCardRarity.Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Épique.
        /// </summary>
        public static string TTGCardRarity_Epic {
            get {
                return ResourceManager.GetString("TTGCardRarity.Epic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string TTGCardRarity_Rare {
            get {
                return ResourceManager.GetString("TTGCardRarity.Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultime.
        /// </summary>
        public static string TTGCardRarity_Ultimate {
            get {
                return ResourceManager.GetString("TTGCardRarity.Ultimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu (#1).
        /// </summary>
        public static string Unknown_Data {
            get {
                return ResourceManager.GetString("Unknown.Data", resourceCulture);
            }
        }
    }
}
