CREATE TABLE IF NOT EXISTS Lang(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Type INTEGER NOT NULL,
    Language INTEGER NOT NULL,
    Name TEXT NOT NULL,
    Version INTEGER NOT NULL,
    IsNew INTEGER NOT NULL CHECK(IsNew IN (0, 1)) DEFAULT 0, -- BOOLEAN
    UNIQUE(Type, Language, Name)
);
