//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyberia.Translations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyberia.Translations.Resources.BotTranslations", typeof(BotTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for .
        /// </summary>
        internal static string _for {
            get {
                return ResourceManager.GetString("for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class not found..
        /// </summary>
        internal static string Breed_NotFound {
            get {
                return ResourceManager.GetString("Breed.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft.
        /// </summary>
        internal static string Button_Craft {
            get {
                return ResourceManager.GetString("Button.Craft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Button_Next {
            get {
                return ResourceManager.GetString("Button.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Button_Previous {
            get {
                return ResourceManager.GetString("Button.Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resimulate.
        /// </summary>
        internal static string Button_Resimulate {
            get {
                return ResourceManager.GetString("Button.Resimulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runes calculator.
        /// </summary>
        internal static string Button_RuneItem {
            get {
                return ResourceManager.GetString("Button.RuneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display subcrafts.
        /// </summary>
        internal static string Button_SubCraft_Display {
            get {
                return ResourceManager.GetString("Button.SubCraft.Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide subcrafts.
        /// </summary>
        internal static string Button_SubCraft_Hide {
            get {
                return ResourceManager.GetString("Button.SubCraft.Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        internal static string Chance {
            get {
                return ResourceManager.GetString("Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command can only be used by the bot owner..
        /// </summary>
        internal static string Command_Error_Check_RequireApplicationOwner {
            get {
                return ResourceManager.GetString("Command.Error.Check.RequireApplicationOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command can only be used in a server..
        /// </summary>
        internal static string Command_Error_Check_RequireGuild {
            get {
                return ResourceManager.GetString("Command.Error.Check.RequireGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control of type #1 for this command failed..
        /// </summary>
        internal static string Command_Error_Check_Unknown {
            get {
                return ResourceManager.GetString("Command.Error.Check.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem creating the reply, the message is probably too old..
        /// </summary>
        internal static string Command_Error_Component {
            get {
                return ResourceManager.GetString("Command.Error.Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command has run into a problem, a bug report has been sent automatically to the bot owner..
        /// </summary>
        internal static string Command_Error_UserResponse {
            get {
                return ResourceManager.GetString("Command.Error.UserResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft not found..
        /// </summary>
        internal static string Craft_NotFound {
            get {
                return ResourceManager.GetString("Craft.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string Embed_Breed_Author {
            get {
                return ResourceManager.GetString("Embed.Breed.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafts calculator.
        /// </summary>
        internal static string Embed_Craft_Author {
            get {
                return ResourceManager.GetString("Embed.Craft.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft :.
        /// </summary>
        internal static string Embed_Craft_Title {
            get {
                return ResourceManager.GetString("Embed.Craft.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical hit calculator.
        /// </summary>
        internal static string Embed_Crit_Author {
            get {
                return ResourceManager.GetString("Embed.Crit.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be #1 at #2 with #3 crit and #4 agi.
        ///To reach 1/2, you will need at least #5 agi..
        /// </summary>
        internal static string Embed_Crit_Description {
            get {
                return ResourceManager.GetString("Embed.Crit.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape % calculator.
        /// </summary>
        internal static string Embed_Escape_Author {
            get {
                return ResourceManager.GetString("Embed.Escape.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With #1 agi, you will have a #2% chance of escape against #3 agi.
        ///To escape at 100%, you will need at minimum #4 agi..
        /// </summary>
        internal static string Embed_Escape_Description {
            get {
                return ResourceManager.GetString("Embed.Escape.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment :.
        /// </summary>
        internal static string Embed_Field_Alignment_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Alignment.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category :.
        /// </summary>
        internal static string Embed_Field_Category_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Category.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustable range.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_AdjustableRange {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.AdjustableRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb. of casts per turn and per player :.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_CastPerPlayer {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.CastPerPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb. of casts per turn :.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_CastPerTurn {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.CastPerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure probability :.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_CriticalFailure {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.CriticalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CF ends turn.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_CriticalFailureEndTurn {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.CriticalFailureEndTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical hit probability :.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_CriticalHit {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.CriticalHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global recast interval.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_GlobalRecast {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.GlobalRecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_Linear {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of sight.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_LineOfSight {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.LineOfSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free squares.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_NeedFreeCell {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.NeedFreeCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb. of turns between two casts :.
        /// </summary>
        internal static string Embed_Field_Characteristics_Content_TurnsBetweenCast {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Content.TurnsBetweenCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristics :.
        /// </summary>
        internal static string Embed_Field_Characteristics_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Characteristics.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest :.
        /// </summary>
        internal static string Embed_Field_Chest_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Chest.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craft :.
        /// </summary>
        internal static string Embed_Field_Craft_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Craft.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 per craft{~2
        ///}#2{~2 in total}.
        /// </summary>
        internal static string Embed_Field_CraftTime_Content {
            get {
                return ResourceManager.GetString("Embed.Field.CraftTime.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approximated craft time :.
        /// </summary>
        internal static string Embed_Field_CraftTime_Title {
            get {
                return ResourceManager.GetString("Embed.Field.CraftTime.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria :.
        /// </summary>
        internal static string Embed_Field_Criteria_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Criteria.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical effects :.
        /// </summary>
        internal static string Embed_Field_CriticalEffects_Title {
            get {
                return ResourceManager.GetString("Embed.Field.CriticalEffects.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog :.
        /// </summary>
        internal static string Embed_Field_Dialog_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Dialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects :.
        /// </summary>
        internal static string Embed_Field_Effects_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Effects.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden states :.
        /// </summary>
        internal static string Embed_Field_ForbiddenStates_Title {
            get {
                return ResourceManager.GetString("Embed.Field.ForbiddenStates.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyph effects :.
        /// </summary>
        internal static string Embed_Field_GlyphEffects_Title {
            get {
                return ResourceManager.GetString("Embed.Field.GlyphEffects.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items :.
        /// </summary>
        internal static string Embed_Field_Items_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Items.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set :.
        /// </summary>
        internal static string Embed_Field_ItemSet_Title {
            get {
                return ResourceManager.GetString("Embed.Field.ItemSet.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type :.
        /// </summary>
        internal static string Embed_Field_ItemType_Title {
            get {
                return ResourceManager.GetString("Embed.Field.ItemType.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level :.
        /// </summary>
        internal static string Embed_Field_Level_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Level.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ceremonial item.
        /// </summary>
        internal static string Embed_Field_Miscellaneous_Content_Ceremonial {
            get {
                return ResourceManager.GetString("Embed.Field.Miscellaneous.Content.Ceremonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cursed.
        /// </summary>
        internal static string Embed_Field_Miscellaneous_Content_Cursed {
            get {
                return ResourceManager.GetString("Embed.Field.Miscellaneous.Content.Cursed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smithmageable.
        /// </summary>
        internal static string Embed_Field_Miscellaneous_Content_Enhanceable {
            get {
                return ResourceManager.GetString("Embed.Field.Miscellaneous.Content.Enhanceable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ethereal item.
        /// </summary>
        internal static string Embed_Field_Miscellaneous_Content_Ethereal {
            get {
                return ResourceManager.GetString("Embed.Field.Miscellaneous.Content.Ethereal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sells for #1 #2 at npcs.
        /// </summary>
        internal static string Embed_Field_Miscellaneous_Content_Price {
            get {
                return ResourceManager.GetString("Embed.Field.Miscellaneous.Content.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is targetable.
        /// </summary>
        internal static string Embed_Field_Miscellaneous_Content_Targetable {
            get {
                return ResourceManager.GetString("Embed.Field.Miscellaneous.Content.Targetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is usable.
        /// </summary>
        internal static string Embed_Field_Miscellaneous_Content_Usable {
            get {
                return ResourceManager.GetString("Embed.Field.Miscellaneous.Content.Usable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pod(s).
        /// </summary>
        internal static string Embed_Field_Miscellaneous_Content_Weight {
            get {
                return ResourceManager.GetString("Embed.Field.Miscellaneous.Content.Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous :.
        /// </summary>
        internal static string Embed_Field_Miscellaneous_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Miscellaneous.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed :.
        /// </summary>
        internal static string Embed_Field_MonsterRaceData_Title {
            get {
                return ResourceManager.GetString("Embed.Field.MonsterRaceData.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecosystem :.
        /// </summary>
        internal static string Embed_Field_MonsterSuperRaceData_Title {
            get {
                return ResourceManager.GetString("Embed.Field.MonsterSuperRaceData.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal level :.
        /// </summary>
        internal static string Embed_Field_OptimalLevel_Title {
            get {
                return ResourceManager.GetString("Embed.Field.OptimalLevel.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Embed_Field_Page_Content {
            get {
                return ResourceManager.GetString("Embed.Field.Page.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal between.
        /// </summary>
        internal static string Embed_Field_Pet_Content_MealBetween {
            get {
                return ResourceManager.GetString("Embed.Field.Pet.Content.MealBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet :.
        /// </summary>
        internal static string Embed_Field_Pet_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Pet.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price :.
        /// </summary>
        internal static string Embed_Field_Price_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Price.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives :.
        /// </summary>
        internal static string Embed_Field_QuestObjectives_Title {
            get {
                return ResourceManager.GetString("Embed.Field.QuestObjectives.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required level :.
        /// </summary>
        internal static string Embed_Field_RequiredLevel_Title {
            get {
                return ResourceManager.GetString("Embed.Field.RequiredLevel.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required states :.
        /// </summary>
        internal static string Embed_Field_RequiredStates_Title {
            get {
                return ResourceManager.GetString("Embed.Field.RequiredStates.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotes :.
        /// </summary>
        internal static string Embed_Field_Rewards_Content_Emotes {
            get {
                return ResourceManager.GetString("Embed.Field.Rewards.Content.Emotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs :.
        /// </summary>
        internal static string Embed_Field_Rewards_Content_Jobs {
            get {
                return ResourceManager.GetString("Embed.Field.Rewards.Content.Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells :.
        /// </summary>
        internal static string Embed_Field_Rewards_Content_Spells {
            get {
                return ResourceManager.GetString("Embed.Field.Rewards.Content.Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards :.
        /// </summary>
        internal static string Embed_Field_Rewards_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Rewards.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room :.
        /// </summary>
        internal static string Embed_Field_Room_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Room.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa rate :.
        /// </summary>
        internal static string Embed_Field_RunePaRate_Title {
            get {
                return ResourceManager.GetString("Embed.Field.RunePaRate.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ra rate :.
        /// </summary>
        internal static string Embed_Field_RuneRaRate_Title {
            get {
                return ResourceManager.GetString("Embed.Field.RuneRaRate.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source :.
        /// </summary>
        internal static string Embed_Field_Source_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Source.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells :.
        /// </summary>
        internal static string Embed_Field_Spells_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Spells.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap effects :.
        /// </summary>
        internal static string Embed_Field_TrapEffects_Title {
            get {
                return ResourceManager.GetString("Embed.Field.TrapEffects.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP :.
        /// </summary>
        internal static string Embed_Field_Weapon_Content_AP {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Content.AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area :.
        /// </summary>
        internal static string Embed_Field_Weapon_Content_Area {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Content.Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure :.
        /// </summary>
        internal static string Embed_Field_Weapon_Content_CriticalFailure {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Content.CriticalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical hit :.
        /// </summary>
        internal static string Embed_Field_Weapon_Content_CriticalHit {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Content.CriticalHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical hit bonus :.
        /// </summary>
        internal static string Embed_Field_Weapon_Content_CriticalHitBonus {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Content.CriticalHitBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear only.
        /// </summary>
        internal static string Embed_Field_Weapon_Content_Linear {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Content.Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No line of sight.
        /// </summary>
        internal static string Embed_Field_Weapon_Content_LineOfSight {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Content.LineOfSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-handed weapon.
        /// </summary>
        internal static string Embed_Field_Weapon_Content_OneHanded {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Content.OneHanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range :.
        /// </summary>
        internal static string Embed_Field_Weapon_Content_Range {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Content.Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-handed weapon.
        /// </summary>
        internal static string Embed_Field_Weapon_Content_TwoHanded {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Content.TwoHanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristics :.
        /// </summary>
        internal static string Embed_Field_Weapon_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Weapon.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 pod(s) per craft{~2, }#2{~2 in total}.
        /// </summary>
        internal static string Embed_Field_Weight_Content {
            get {
                return ResourceManager.GetString("Embed.Field.Weight.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight :.
        /// </summary>
        internal static string Embed_Field_Weight_Title {
            get {
                return ResourceManager.GetString("Embed.Field.Weight.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estate agency.
        /// </summary>
        internal static string Embed_House_Author {
            get {
                return ResourceManager.GetString("Embed.House.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incarnations.
        /// </summary>
        internal static string Embed_Incarnation_Author {
            get {
                return ResourceManager.GetString("Embed.Incarnation.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incarnation not existing in the game data..
        /// </summary>
        internal static string Embed_Incarnation_Description_NotFound {
            get {
                return ResourceManager.GetString("Embed.Incarnation.Description.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Embed_Item_Author {
            get {
                return ResourceManager.GetString("Embed.Item.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        internal static string Embed_ItemSet_Author {
            get {
                return ResourceManager.GetString("Embed.ItemSet.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World map.
        /// </summary>
        internal static string Embed_Map_Author {
            get {
                return ResourceManager.GetString("Embed.Map.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestiary.
        /// </summary>
        internal static string Embed_Monster_Author {
            get {
                return ResourceManager.GetString("Embed.Monster.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple crafts found :.
        /// </summary>
        internal static string Embed_PaginatedCraft_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedCraft.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple houses found :.
        /// </summary>
        internal static string Embed_PaginatedHouse_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedHouse.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple incarnations found :.
        /// </summary>
        internal static string Embed_PaginatedIncarnation_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedIncarnation.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple items found :.
        /// </summary>
        internal static string Embed_PaginatedItem_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedItem.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sets found :.
        /// </summary>
        internal static string Embed_PaginatedItemSet_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedItemSet.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple maps found :.
        /// </summary>
        internal static string Embed_PaginatedMap_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedMap.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple areas found :.
        /// </summary>
        internal static string Embed_PaginatedMapArea_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedMapArea.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple subareas found :.
        /// </summary>
        internal static string Embed_PaginatedMapSubArea_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedMapSubArea.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple monsters found :.
        /// </summary>
        internal static string Embed_PaginatedMonster_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedMonster.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple quests found :.
        /// </summary>
        internal static string Embed_PaginatedQuest_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedQuest.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple spells found :.
        /// </summary>
        internal static string Embed_PaginatedSpell_Title {
            get {
                return ResourceManager.GetString("Embed.PaginatedSpell.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest book.
        /// </summary>
        internal static string Embed_Quest_Author {
            get {
                return ResourceManager.GetString("Embed.Quest.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runes calculator.
        /// </summary>
        internal static string Embed_Rune_Author {
            get {
                return ResourceManager.GetString("Embed.Rune.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 #2% chance on a level #3 item with #4 stats..
        /// </summary>
        internal static string Embed_Rune_Description_Multiple {
            get {
                return ResourceManager.GetString("Embed.Rune.Description.Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 #2% chance on a level #3 item..
        /// </summary>
        internal static string Embed_Rune_Description_One {
            get {
                return ResourceManager.GetString("Embed.Rune.Description.One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune generation simulation :.
        /// </summary>
        internal static string Embed_RuneItem_Description {
            get {
                return ResourceManager.GetString("Embed.RuneItem.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells book.
        /// </summary>
        internal static string Embed_Spell_Author {
            get {
                return ResourceManager.GetString("Embed.Spell.Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  from .
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House not found..
        /// </summary>
        internal static string House_NotFound {
            get {
                return ResourceManager.GetString("House.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no house at [#1, #2]..
        /// </summary>
        internal static string House_NotFound_Coordinate {
            get {
                return ResourceManager.GetString("House.NotFound.Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The #1 area does not contain any house..
        /// </summary>
        internal static string House_NotFound_MapArea {
            get {
                return ResourceManager.GetString("House.NotFound.MapArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The #1 subarea does not contain any house..
        /// </summary>
        internal static string House_NotFound_MapSubArea {
            get {
                return ResourceManager.GetString("House.NotFound.MapSubArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incarnation not found..
        /// </summary>
        internal static string Incarnation_NotFound {
            get {
                return ResourceManager.GetString("Incarnation.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter.
        /// </summary>
        internal static string IncorrectParameter {
            get {
                return ResourceManager.GetString("IncorrectParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        internal static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found..
        /// </summary>
        internal static string Item_NotFound {
            get {
                return ResourceManager.GetString("Item.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set not found..
        /// </summary>
        internal static string ItemSet_NotFound {
            get {
                return ResourceManager.GetString("ItemSet.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your language has been modified to #1..
        /// </summary>
        internal static string Language_Set {
            get {
                return ResourceManager.GetString("Language.Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map not found..
        /// </summary>
        internal static string Map_NotFound {
            get {
                return ResourceManager.GetString("Map.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no map at [#1, #2]..
        /// </summary>
        internal static string Map_NotFound_Coordinate {
            get {
                return ResourceManager.GetString("Map.NotFound.Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The #1 area does not contain any map..
        /// </summary>
        internal static string Map_NotFound_MapArea {
            get {
                return ResourceManager.GetString("Map.NotFound.MapArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The #1 subarea does not contain any map..
        /// </summary>
        internal static string Map_NotFound_MapSubArea {
            get {
                return ResourceManager.GetString("Map.NotFound.MapSubArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area not found..
        /// </summary>
        internal static string MapArea_NotFound {
            get {
                return ResourceManager.GetString("MapArea.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subarea not found..
        /// </summary>
        internal static string MapSubArea_NotFound {
            get {
                return ResourceManager.GetString("MapSubArea.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster not found..
        /// </summary>
        internal static string Monster_NotFound {
            get {
                return ResourceManager.GetString("Monster.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible values :.
        /// </summary>
        internal static string PossibleValues {
            get {
                return ResourceManager.GetString("PossibleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest not found..
        /// </summary>
        internal static string Quest_NotFound {
            get {
                return ResourceManager.GetString("Quest.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the personal information currently stored about you:.
        /// </summary>
        internal static string Rgpd_Data {
            get {
                return ResourceManager.GetString("Rgpd.Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your personal data has been deleted..
        /// </summary>
        internal static string Rgpd_Deleted {
            get {
                return ResourceManager.GetString("Rgpd.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personal data is currently stored about you..
        /// </summary>
        internal static string Rgpd_NoData {
            get {
                return ResourceManager.GetString("Rgpd.NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item to calculate its craft.
        /// </summary>
        internal static string Select_Craft_Placeholder {
            get {
                return ResourceManager.GetString("Select.Craft.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a house to display it.
        /// </summary>
        internal static string Select_House_Placeholder {
            get {
                return ResourceManager.GetString("Select.House.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoors.
        /// </summary>
        internal static string Select_HouseMap_Option_Outdoors {
            get {
                return ResourceManager.GetString("Select.HouseMap.Option.Outdoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Select_HouseMap_Option_Room {
            get {
                return ResourceManager.GetString("Select.HouseMap.Option.Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a room do display it.
        /// </summary>
        internal static string Select_HouseMap_Placeholder {
            get {
                return ResourceManager.GetString("Select.HouseMap.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an incarnation to display it.
        /// </summary>
        internal static string Select_Incarnation_Placeholder {
            get {
                return ResourceManager.GetString("Select.Incarnation.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item to display it.
        /// </summary>
        internal static string Select_Item_Placeholder {
            get {
                return ResourceManager.GetString("Select.Item.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a set to display it.
        /// </summary>
        internal static string Select_ItemSet_Placeholder {
            get {
                return ResourceManager.GetString("Select.ItemSet.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a map to display it.
        /// </summary>
        internal static string Select_Map_Placeholder {
            get {
                return ResourceManager.GetString("Select.Map.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an area to display its maps.
        /// </summary>
        internal static string Select_MapArea_Placeholder {
            get {
                return ResourceManager.GetString("Select.MapArea.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a subarea to display its maps.
        /// </summary>
        internal static string Select_MapSubArea_Placeholder {
            get {
                return ResourceManager.GetString("Select.MapSubArea.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a monster to display it.
        /// </summary>
        internal static string Select_Monster_Placeholder {
            get {
                return ResourceManager.GetString("Select.Monster.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a quest to display it.
        /// </summary>
        internal static string Select_Quest_Placeholder {
            get {
                return ResourceManager.GetString("Select.Quest.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string Select_QuestStep_Content_Step {
            get {
                return ResourceManager.GetString("Select.QuestStep.Content.Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a step to display it.
        /// </summary>
        internal static string Select_QuestStep_Placeholder {
            get {
                return ResourceManager.GetString("Select.QuestStep.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item to calculate the runes that can be obtained.
        /// </summary>
        internal static string Select_RuneItem_Placeholder {
            get {
                return ResourceManager.GetString("Select.RuneItem.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a spell to display it.
        /// </summary>
        internal static string Select_Spell_Placeholder {
            get {
                return ResourceManager.GetString("Select.Spell.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP.
        /// </summary>
        internal static string ShortActionPoint {
            get {
                return ResourceManager.GetString("ShortActionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg..
        /// </summary>
        internal static string ShortAverage {
            get {
                return ResourceManager.GetString("ShortAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inf..
        /// </summary>
        internal static string ShortInfinity {
            get {
                return ResourceManager.GetString("ShortInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv..
        /// </summary>
        internal static string ShortLevel {
            get {
                return ResourceManager.GetString("ShortLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max..
        /// </summary>
        internal static string ShortMaximum {
            get {
                return ResourceManager.GetString("ShortMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min..
        /// </summary>
        internal static string ShortMinimum {
            get {
                return ResourceManager.GetString("ShortMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA.
        /// </summary>
        internal static string ShortRange {
            get {
                return ResourceManager.GetString("ShortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell not found..
        /// </summary>
        internal static string Spell_NotFound {
            get {
                return ResourceManager.GetString("Spell.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon.
        /// </summary>
        internal static string Summon {
            get {
                return ResourceManager.GetString("Summon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to .
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitality.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        internal static string Wisdom {
            get {
                return ResourceManager.GetString("Wisdom", resourceCulture);
            }
        }
    }
}
