//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyberia.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyberia.Translations.Resources.WebTranslations", typeof(WebTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by #1.
        /// </summary>
        public static string Layout_DevelopedBy {
            get {
                return ResourceManager.GetString("Layout.DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a fansite not affiliated with.
        /// </summary>
        public static string Layout_NotAffiliated {
            get {
                return ResourceManager.GetString("Layout.NotAffiliated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeds.
        /// </summary>
        public static string Page_Breeds_Title {
            get {
                return ResourceManager.GetString("Page.Breeds.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeons.
        /// </summary>
        public static string Page_Dungeons_Title {
            get {
                return ResourceManager.GetString("Page.Dungeons.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Page_Index_Title {
            get {
                return ResourceManager.GetString("Page.Index.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Page_Items_Title {
            get {
                return ResourceManager.GetString("Page.Items.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monsters.
        /// </summary>
        public static string Page_Monsters_Title {
            get {
                return ResourceManager.GetString("Page.Monsters.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        public static string Page_Quests_Title {
            get {
                return ResourceManager.GetString("Page.Quests.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        public static string Page_Spells_Title {
            get {
                return ResourceManager.GetString("Page.Spells.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Page_Tools_Title {
            get {
                return ResourceManager.GetString("Page.Tools.Title", resourceCulture);
            }
        }
    }
}
