//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyberia.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyberia.Translations.Resources.WebTranslations", typeof(WebTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection.
        /// </summary>
        public static string Layout_CultureSelection {
            get {
                return ResourceManager.GetString("Layout.CultureSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by #1.
        /// </summary>
        public static string Layout_DevelopedBy {
            get {
                return ResourceManager.GetString("Layout.DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a fansite not affiliated with.
        /// </summary>
        public static string Layout_NotAffiliated {
            get {
                return ResourceManager.GetString("Layout.NotAffiliated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeds.
        /// </summary>
        public static string Page_Breeds_Title {
            get {
                return ResourceManager.GetString("Page.Breeds.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeons.
        /// </summary>
        public static string Page_Dungeons_Title {
            get {
                return ResourceManager.GetString("Page.Dungeons.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Page_Index_Title {
            get {
                return ResourceManager.GetString("Page.Index.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Page_Items_Title {
            get {
                return ResourceManager.GetString("Page.Items.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monsters.
        /// </summary>
        public static string Page_Monsters_Title {
            get {
                return ResourceManager.GetString("Page.Monsters.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        public static string Page_Quests_Title {
            get {
                return ResourceManager.GetString("Page.Quests.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salamandra.
        /// </summary>
        public static string Page_Salamandra_Title {
            get {
                return ResourceManager.GetString("Page.Salamandra.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;1. Consent&lt;/h3&gt;
        ///&lt;p&gt;By using Salamandra, you agree to the following privacy policy.&lt;/p&gt;
        ///&lt;h3&gt;2. What information is stored&lt;/h3&gt;
        ///&lt;p&gt;None.&lt;/p&gt;
        ///&lt;h3&gt;3. How we use your information&lt;/h3&gt;
        ///&lt;p&gt;We don&apos;t use your information.&lt;/p&gt;
        ///&lt;h3&gt;4. Temporarily stored Information&lt;/h3&gt;
        ///&lt;p&gt;Salamandra may keep information in an internal caching mechanic for a certain amount of time.&lt;br&gt;
        ///After this time period, the cached information will be dropped and only be re-added when required.&lt;/p&gt;
        ///&lt;h3&gt;5. Questions and Concerns&lt;/h3&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Page_SalamandraPrivacy_Content {
            get {
                return ResourceManager.GetString("Page.SalamandraPrivacy.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Page_SalamandraPrivacy_Title {
            get {
                return ResourceManager.GetString("Page.SalamandraPrivacy.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;1. Terms&lt;/h3&gt;
        ///&lt;p&gt;By using this Bot you are agreeing to be bound by these Terms of service and agree that you are responsible for the agreement with any applicable local laws. If you disagree with any of these terms, you are prohibited from using this bot.&lt;/p&gt;
        ///&lt;h3&gt;2. Disclaimer&lt;/h3&gt;
        ///&lt;p&gt;All Salamandra materials are provided &quot;as is&quot;. Salamandra makes no warranties, expressed or implied, and therefore disclaims all other warranties. Further, Salamandra makes no representations concerning the accuracy or  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Page_SalamandraTos_Content {
            get {
                return ResourceManager.GetString("Page.SalamandraTos.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of service.
        /// </summary>
        public static string Page_SalamandraTos_Title {
            get {
                return ResourceManager.GetString("Page.SalamandraTos.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        public static string Page_Spells_Title {
            get {
                return ResourceManager.GetString("Page.Spells.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Page_Tools_Title {
            get {
                return ResourceManager.GetString("Page.Tools.Title", resourceCulture);
            }
        }
    }
}
