name: Build

on:
  push:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build-validation.yml"
      - "Cyberia*/**"
      - "*.sln"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
        
      - name: Build
        run: dotnet build -c Release

      - name: Add execution right on Flare
        run: ls -la

      - name: Test
        run: dotnet test --no-build -c Release -l "console;verbosity=detailed"
