name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
        
      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test --no-build -c Release

      - name: Publish
        run: dotnet publish Cyberia/Cyberia.csproj --no-build -c Release -o ./Salamandra
    
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ./Salamandra
          target: /home/salamandra

      - name: Add execution right on Flare
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: chmod -R 755 /home/salamandra/Salamandra/flare
