name: Publish

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FOLDER: Lapichon

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish Salamandra.sln --configuration Release --output ./$FOLDER
    
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ./$FOLDER
        target: /home/${{ secrets.SSH_USER }}/

    - name: Add execution right on Flare
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: chmod -R 755 /home/${{ secrets.SSH_HOST }}/$FOLDER/langs/flare
